"""Added column tables

Revision ID: ededd604452a
Revises: 8284bf517363
Create Date: 2023-09-29 18:18:40.030849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ededd604452a'
down_revision = '8284bf517363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients', sa.String(), nullable=True))
        batch_op.drop_column('ingridients')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingridients', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('ingredients')

    # ### end Alembic commands ###
